# main site metadata and titles
site_name: Miss Devanna Rajeswari
site_description: Consultant Gynaecologist & Obstetrician
site_author: Dr Anchit Chandran
site_url: https://anchit-chandran.github.io/dr-rajeswari-website/

# copyright information which is shown in the footer
copyright: Copyright &copy; 2023 Devanna Rajeswari.

# these lines configure the 'GitHub repo' widget on the top right
# repo_url: https://github.com/anchit-chandran/medicode-website
# repo_name: anchit-chandran/medicode-website

# `mkdocs serve` serves the documentation at custom port
dev_addr: "127.0.0.1:8001"

nav:
  - Home: "index.md"
  - "about.md"
  - Testimonials:
      - "Custom ID": '/#testimonials'
  - Conditions: "conditions.md"
  - Contact: "contact.md"

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate
    - toc.follow
  palette:
    scheme: dark
  font:
    text: Lustria
    code: Roboto Mono
  logo: _assets/_images/logo.png
  favicon: _assets/_images/logo.png

# additional directories to watch when running `mkdocs serve`
watch:
  - overrides

extra_files:
  - CNAME

extra_css:
  - _assets/_stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator:
        !!python/name:materialx.emoji.to_svg # footer links and variables

extra:
  social:
    - icon: fontawesome/brands/twitter
      # link: https://twitter.com/medic_ode
    - icon: fontawesome/brands/instagram
      # link: https://www.instagram.com/medic_ode/
